name: Tests

on: [push, pull_request]

jobs:
  test:
    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.0', '8.1', '8.2', '8.3']
        laravel: ['8.*', '9.*', '10.*', '11.*', '12.*']
        exclude:
          # Exclude incompatible combinations
          - php: '8.0'
            laravel: '12.*'
          - php: '8.1'
            laravel: '12.*'
        include:
          # Add specific testbench versions
          - laravel: '8.*'
            testbench: '6.*'
          - laravel: '9.*'
            testbench: '7.*'
          - laravel: '10.*'
            testbench: '8.*'
          - laravel: '11.*'
            testbench: '9.*'
          - laravel: '12.*'
            testbench: '10.*'

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring
          tools: composer:v2

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-progress
          composer install --no-interaction --no-progress

      - name: Run tests
        run: vendor/bin/phpunit