name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['8.0', '8.1', '8.2', '8.3', '8.4']
        laravel: ['8.*', '9.*', '10.*', '11.*', '12.*']
        exclude:
          # Exclude Laravel 12.* for PHP versions that don't support it
          - php: '8.0'
            laravel: '12.*'

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, dom, curl
          coverage: none

      - name: Install dependencies
        run: |
          composer require illuminate/support:${{ matrix.laravel }} --no-update
          composer update --prefer-stable --no-interaction --no-suggest

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --testdox
