name: Test Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['8.0', '8.1', '8.2', '8.3']
        laravel: ['^8.0', '^9.0', '^10.0', '^11.0', '^12.0']
        include:
          - laravel: '^12.1'
            php: '8.2'
          - laravel: '^12.1'
            php: '8.3'
        exclude:
          - php: '8.0'
            laravel: '^12.0'
          - php: '8.0'
            laravel: '^12.1'
          - php: '8.1'
            laravel: '^12.1'

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, dom, fileinfo
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit